### PR TITLE
Update post.js

### PR DESCRIPTION
**Pull request by mikermcneil**
This is a template for what we could do to all of the shortcut machines.

+ change friendly name (`Send HTTP POST request` => `POST`)
+ Added extendedDescription
+ `body` input => `data`  (See jquery)
  + Note that `sendHttpRequest` still accepts `body` -- we map this in the impl
+ In success exit, send back only response body (see jquery-- for more advanced use cases, we can use sendHttpRequest, see extendedDescription)
+ expect `sendHttpRequest` to use the same exits as this machine (this will require additional changes in sendHttpRequest)
+ for `non200Response`:
  + change `status` => `statusCode` for clarity mainly, but also for consistency w/ our other conventions (e.g.  in mp-routes, but also just https://nodejs.org/api/http.html#http_response_statuscode)
  + expect headers to be pre-parsed (string => `{}`)  (this is annoying to do by hand-- we should do it in the simpler machines as well as in the lower level `sendHttpRequest`)
  +

### CODE REVIEW

**Comment by mikermcneil** [comment]
@sgress454 As a follow up, I also added some improved error handling to this machine.  Assuming I'm not missing anything, I think this is an approach we can emulate to send back better errors in the other machines as well.

**Comment by mikermcneil** [comment]
@sgress454 Whoops, just noticed that the `invalid` exit was removed from mp-urls: https://github.com/mikermcneil/machinepack-urls/commit/793ad6529b84b4a5b8dfcfd44cf2b5bd96e0107f

Since we haven't updated the dep here yet, this PR technically still works.  But I also understand the thinking in that commit in mp-urls.  On one hand, I think it does make sense to still have access to the `invalid` exit from `Urls.resolve()` -- because then we could handle that here, for example, to provide a more useful error message.  But, like you pointed out there-- it's totally possible to call `.validate()` first, meaning that there's a way to work around it.  So I think it's fine (esp. assuming that's the approach you've been using elsewhere, which it looks like it is)

But what I will do is:
1. Send a PR to mp-urls that improves the error message in mp-urls/resolve.  (Our use case in mp-http is generic enough we can just use what I put in this PR as the default error message in mp-urls)
2. Change this PR so that it does not rely on the `invalid` exit from mp-urls/resolve

**Comment by mikermcneil** [comment]
@sgress454 ok here's the PR to mp-urls: https://github.com/mikermcneil/machinepack-urls/pull/2  (also includes a vaguely related change-- removing out of date verbiage from the extended description)

Also, 96e31090fce680bf98f5be1675088025c76b861f in this PR removes the reliance on the `invalid` exit from mp-urls.  I tested that, and it looks just as good.  The stack trace is slightly more annoying, but it's fine (and anyway, it's only noticeable because of the extra baggage inserted by the machine runner -- which we should tackle as a separate adventure at some point.)

I went ahead and published mp-urls@6.0.0-0 (as beta), and hooked it up in the package.json.  While I was there, I also pinned all external deps, normalized the lodash version, and bumped the machine runner dep's semver range.  That's all in 61a9ee3e33bc82c288acfe1c492c1f1c004461e8.

Obviously, there's more work to do as far as normalizing these changes across the other machines (the stuff I mentioned above), but other than that, this PR is ready to merge, as far as I'm concerned.

**Comment by sgress454** [comment]
@mikermcneil I'm ok with everything except `body` => `data` -- it's not always clear who we're building these machines for, but I built this based on the conventions in mikeal's request, not jQuery, because it seems like our initial market right now is Noders more than front-end people.  And in the absence of really compelling reasons to change something like this,  I don't think we should.

**Comment by mikermcneil** [comment]
@sgress454 About to push a few more commits as a follow up to an [update I posted in mp-urls](https://github.com/mikermcneil/machinepack-urls/pull/3#issuecomment-246199866).  Will add more exposition in a bit.

**Pull request merged**
